### ISSUE TITLE
Starting the Home Screen 2 - Featured Recipe Tab

### ISSUE THREAD

**Issue by andersontan1998** [HealthyChef/Healthy_Chef#6]
References: https://www.youtube.com/watch?v=FuQJ4SJYsaU&list=PLrT2tZ9JRrf70K7LrG475BFDYq44_1Kpa&index=2

Start the main activity page consisting of featured recipes also known as the Home page.
Part 1 creates part of the Home page. Part 2 (this issue) implements the tabs.

- [x] Implement tabs/fragments on the bottom of the screen, refer to the YouTube link.

**Comment by aakter** [comment]
done.
